# -*- coding: utf-8 -*-
"""portland_weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ0IbzFhDb2ngyaGujsAKB3F_tggNEkg
"""

#Import the requests library
import requests

# Store your OpenWeatherMap API key securely
api_key = "ed53bb821637bf984e5bbba82ae507fd"

#Set coordinates for Portland, OR
lat = 45.5155
lon = -122.6777

#Build the API endpoint URL
base_url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"

#Make the GET request to the API
response = requests.get(base_url)

#If the response is successful, process the JSON
if response.status_code == 200:
    data = response.json()

    #Extract the current weather condition
    current_condition = data["weather"][0]["main"]

    # Check if it's raining
    if current_condition.lower() in ["rain", "drizzle", "thunderstorm"]:
        print("☔ Yes, it is currently raining in Portland, OR.")
    else:
        print("🌤 No, it is not currently raining in Portland, OR.")

    # OPTIONAL: Show more info
    print(f"\nCurrent condition: {current_condition}")
    print(f"Location: {data['name']}, {data['sys']['country']}")
    print(f"Temperature: {round(data['main']['temp'] - 273.15, 1)} °C")
else:
    print(f"API Error: {response.status_code}")
    print("Details:", response.json())